package uk.ac.brunel.spaceport.ui;

public enum FederateMessageType {
    BRUNEL_SPACEPORT_BEACON_ACKNOWLEDGED,
    BRUNEL_SPACEPORT_CABLECAR_LANDER_TOUCHDOWN,
    BRUNEL_SPACEPORT_LANDER_ARRIVAL_ACKNOWLEDGED,
    BRUNEL_SPACEPORT_LANDER_TOUCHDOWN_ACKNOWLEDGED,
    BRUNEL_SPACEPORT_LANDER_DEPARTURE_ACKNOWLEDGED,

    UCF_BEACON_SPACEPORT_LANDER_APPROACHING,
    FACENS_CABLECAR_SPACEPORT_ACKNOWLEDGED,
    BRUNEL_LANDER_SPACEPORT_REQUEST_LANDING,
    BRUNEL_LANDER_SPACEPORT_TOUCHDOWN,
    BRUNEL_LANDER_SPACEPORT_NOTIFY_DEPARTURE;

    public static String getValue(FederateMessageType messageType) {
        return switch (messageType) {
            case BRUNEL_SPACEPORT_BEACON_ACKNOWLEDGED -> "BRUNEL_SPACEPORT_BEACON_ACKNOWLEDGED";
            case BRUNEL_SPACEPORT_CABLECAR_LANDER_TOUCHDOWN -> "BRUNEL_SPACEPORT_CABLECAR_LANDER_TOUCHDOWN";
            case BRUNEL_SPACEPORT_LANDER_ARRIVAL_ACKNOWLEDGED -> "BRUNEL_SPACEPORT_LANDER_ARRIVAL_ACKNOWLEDGED";
            case BRUNEL_SPACEPORT_LANDER_TOUCHDOWN_ACKNOWLEDGED -> "BRUNEL_SPACEPORT_LANDER_TOUCHDOWN_ACKNOWLEDGED";
            case BRUNEL_SPACEPORT_LANDER_DEPARTURE_ACKNOWLEDGED -> "BRUNEL_SPACEPORT_LANDER_DEPARTURE_ACKNOWLEDGED";

            case UCF_BEACON_SPACEPORT_LANDER_APPROACHING ->  "UCF_BEACON_SPACEPORT_LANDER_APPROACHING";
            case FACENS_CABLECAR_SPACEPORT_ACKNOWLEDGED ->   "FACENS_CABLECAR_SPACEPORT_ACKNOWLEDGED";
            case BRUNEL_LANDER_SPACEPORT_REQUEST_LANDING ->  "BRUNEL_LANDER_SPACEPORT_REQUEST_LANDING";
            case BRUNEL_LANDER_SPACEPORT_TOUCHDOWN ->   "BRUNEL_LANDER_SPACEPORT_TOUCHDOWN";
            case BRUNEL_LANDER_SPACEPORT_NOTIFY_DEPARTURE -> "BRUNEL_LANDER_SPACEPORT_NOTIFY_DEPARTURE";
        };
    }
}
