package uk.ac.brunel.spaceport.ui;

public enum FederateMessageType {
    BRUNEL_SPACEPORT_BEACON_ACKNOWLEDGED,
    BRUNEL_SPACEPORT_CABLECAR_LANDER_TOUCHDOWN,
    BRUNEL_SPACEPORT_LANDER_ARRIVAL_ACKNOWLEDGED,
    BRUNEL_SPACEPORT_LANDER_TOUCHDOWN_ACKNOWLEDGED,
    BRUNEL_SPACEPORT_LANDER_REQUEST_DEPARTURE,

    UCF_BEACON_SPACEPORT_LANDER_APPROACHING,
    FACENS_CABLECAR_SPACEPORT_ACKNOWLEDGED,
    BRUNEL_LANDER_SPACEPORT_REQUEST_LANDING,
    BRUNEL_LANDER_SPACEPORT_TOUCHDOWN,
    BRUNEL_LANDER_SPACEPORT_DEPARTURE_COMPLETED;
}
